### ISSUE TITLE
how to visualize STGM predictions along with other methods as fig4 in the paper

### ISSUE THREAD

**Issue by Weijiang-Xiong** [Mouradost/STGM#3]
First, thank you so much for this splendid code base! It is by far the most elegantly structured one in all traffic prediction repos I've seen. 

This is more of curiosity rather than an issue, I noticed there are nice functions in `helper/viz.py` to plot the predictions along with groundtruth. Is it the case that you run MTGNN separatrely using its own opensource implementation, keep the results and draw them together with STGM? Because it seems MTGNN repos doesn't have a nice inference interface as yours. (although it won't be too hard to save the results) 

Thanks! 

https://github.com/nnzhan/MTGNN

**Comment by Mouradost** [comment]
You're welcome, that's my pleasure :).

Actually, I have my own implementation which follows closely the [MTGNN implementation](https://github.com/nnzhan/MTGNN) and likewise for all other baselines, I didn't include them since they are implemented by their owners. However, you can either implement the model logic using the [Model template](https://github.com/Mouradost/STGM/tree/main#-model-) and train it with this repo, or copy [MTGNN](https://github.com/nnzhan/MTGNN) model implementation while modifying the model as follows:
```python
# MTGNN source implementation
class gtnet(nn.Module):
    def __init__(self, gcn_true, buildA_true, gcn_depth, num_nodes, device, predefined_A=None, static_feat=None, dropout=0.3, subgraph_size=20, node_dim=40, dilation_exponential=1, conv_channels=32, residual_channels=32, skip_channels=64, end_channels=128, seq_length=12, in_dim=2, out_dim=12, layers=3, propalpha=0.05, tanhalpha=3, layer_norm_affline=True):
  ...
def forward(self, input, idx=None): 
   ...
# Modification needed
from models.base import BaseModel
class gtnet(BaseModel):
    def __init__(self, gcn_true, buildA_true, gcn_depth, num_nodes, device, predefined_A=None, static_feat=None, dropout=0.3, subgraph_size=20, node_dim=40, dilation_exponential=1, conv_channels=32, residual_channels=32, skip_channels=64, end_channels=128, seq_length=12, in_dim=2, out_dim=12, layers=3, propalpha=0.05, tanhalpha=3, layer_norm_affline=True, channels_last=True, device="cpu", *args, **kwargs):
      super().__init__(name="MTGNN", channels_last=channels_last, use_super_node=False, device=device)
  ...
# NOTE: MTGNN idx parameter is different from STGM idx param
# MTGNN idx -> ids of the adj
# STGM idx -> timestemps day, time ids
# so you need to change the param name
def forward(self, x, adj_idx=None, *args, **kwargs):
  ...
```

You will need to provide the hydra config for MTGNN under `src/config/model/mtgnn.yaml` in-order to train it with the provided trainer. As a last resource, you can provide your own custom trainer for [MTGNN](https://github.com/nnzhan/MTGNN) following the [Trainer template](https://github.com/Mouradost/STGM/tree/main#-trainer-).

Concerning the visualization, after saving your ground and predictions as `prediction.pt` (it is done automatically if you use our implementation) you have two choices:
- Visualize MTGNN prediction vs. ground:
  ```python
  from pathlib import Path
  import torch
  from helpers.viz import init_plot, plot_predictions
  
  init_plot("paper")
  path = Path.home() / "YOUR_PATH_TO_SAVED_PREDICTIONS"
  preds = torch.load(path / "predictions.pt")
  plot_predictions(*preds, return_fig=False)
  ```
- Visualize MTGNN prediction vs STGM or YOUR MODELS PREDICTION vs. ground:
  ```python
  from pathlib import Path
  import torch
  from helpers.viz import init_plot, plot

  init_plot("paper")
  # Constants
  STEP, NODE = 11, 0
  # Path to the folder containing all model's predictions
  path = Path.home() / "YOUR_PATH_TO_SAVED_PREDICTIONS"
  # All model's name
  models_name = ["MTGNN", "STGM", ...]
  preds = []
  # Assuming that each model perdiction is under MODEL_NAME folder
  for model_name in models_name:
    preds, ground = torch.load(path / f"{model_name}" / "predictions.pt")
    preds.append(pred[:, STEP, NODE, 0])

  plot(
    data_timestamps=torch.arange(ground.shape[0]), 
    data=(*preds, ground[:, STEP, NODE, 0]),
    labels=(*models_name, "Ground")
  )
  ```

**Comment by Weijiang-Xiong** [comment]
Thank you for the detailed instructions, I would first try to save the results as you suggested

**Comment by Mouradost** [comment]
Happy to help, feel free to ask additional details if you have troubles in the future.

Good luck
