### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by OvOYu** [Mouradost/STGM#4]
hi can you provide the dataset,thanks

**Comment by Mouradost** [comment]
Hello,
We don't provide the datasets, since they are broadly available. Here is some links to PEMS-Bay and METR-LA.
- [Provided by DCRNN](https://drive.google.com/drive/folders/10FOTa6HXPqX8Pf5WRoRwcFnW9BrNZEIX)
- [Provided by STEP](https://drive.google.com/file/d/1PY7IZ3SchpyXfNIXs71A2GEV29W5QCv2/view)

Hope it helps :)

**Comment by OvOYu** [comment]
thank you very much！

**Comment by OvOYu** [comment]
hello,Could you please tell me which article STEP refers to

**Comment by OvOYu** [comment]
Thank you May I ask if there is any quick channel to contact you? I look forward to helping each other and making progress
