### ISSUE TITLE
About PEMSD7 distance_csv

### ISSUE THREAD

**Issue by OvOYu** [Mouradost/STGM#5]
Regarding this data set, I only found the speed file and the latitude and longitude information of the site in the STGCN paper. May I ask whether you processed the distance file obtained by processing the latitude and longitude information yourself or provided it in someone else’s work. I look forward to your reply. If you processed it, can you provide the relevant code for learning?

**Comment by Mouradost** [comment]
To be frank, I don't remember since I have prepared the datasets in the beginning of my Ph.D. a few years ago, but I'm sure that it's widely available now on the web.
I'm a bit busy with writing my thesis you can reopen this issue in  the future if you struggle to find or extract the distance from Lat and Long matrix.
